
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'INTEGER FLOAT VOLUME CONCENTRATION WORDbuffer : INTEGER VOLUME rgenrgen : reagent rgen\n             | reagentcompound : WORD compound\n                | WORDconcentration : INTEGER CONCENTRATIONreagent : compound concentration'
    
_lr_action_items = {'VOLUME':([2,],[3,]),'INTEGER':([0,4,7,8,],[2,-5,10,-4,]),'CONCENTRATION':([10,],[12,]),'WORD':([3,4,6,11,12,],[4,4,4,-7,-6,]),'$end':([1,5,6,9,11,12,],[0,-1,-3,-2,-7,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'buffer':([0,],[1,]),'rgen':([3,6,],[5,9,]),'concentration':([7,],[11,]),'compound':([3,4,6,],[7,8,7,]),'reagent':([3,6,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> buffer","S'",1,None,None,None),
  ('buffer -> INTEGER VOLUME rgen','buffer',3,'p_buffer','Buffr.py',48),
  ('rgen -> reagent rgen','rgen',2,'p_rgen','Buffr.py',60),
  ('rgen -> reagent','rgen',1,'p_rgen','Buffr.py',61),
  ('compound -> WORD compound','compound',2,'p_compound','Buffr.py',69),
  ('compound -> WORD','compound',1,'p_compound','Buffr.py',70),
  ('concentration -> INTEGER CONCENTRATION','concentration',2,'p_concentration','Buffr.py',74),
  ('reagent -> compound concentration','reagent',2,'p_reagent','Buffr.py',85),
]
